FROM quay.io/centos/centos:stream8

RUN dnf update -y && dnf install -y openssh-server python3 iproute passwd && yum clean all && rm -rf /var/cache/yum
RUN echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    ssh-keygen -A && \
    echo "password" | passwd --stdin root && \
    echo "alias ll='ls -l'" > /etc/profile.d/ll.sh

CMD ["/usr/sbin/sshd", "-D"]

EXPOSE 22

